### ISSUE TITLE
name  = model_def.model.toLowerCase(),

### ISSUE THREAD

**Issue by BransonGitomeh** [devinivy/waterline-fixtures#3]
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at /home/branie/Desktop/sabek/node_modules/waterline-fixtures/lib/index.js:123:28
    at /home/branie/Desktop/sabek/node_modules/async/lib/async.js:699:13
    at iterate (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:275:9)
    at Object.async.series (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:698:15)
    at /home/branie/Desktop/sabek/node_modules/waterline-fixtures/lib/index.js:105:10
    at /home/branie/Desktop/sabek/node_modules/async/lib/async.js:673:13
    at /home/branie/Desktop/sabek/node_modules/async/lib/async.js:230:13
    at _arrayEach (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:81:9)
    at _each (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:72:13)
    at async.forEachOf.async.eachOf (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:229:9)
    at _parallel (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:672:9)
    at Object.async.parallel (/home/branie/Desktop/sabek/node_modules/async/lib/async.js:687:9)
    at process_all (/home/branie/Desktop/sabek/node_modules/waterline-fixtures/lib/index.js:77:8)
    at /home/branie/Desktop/sabek/node_modules/waterline-fixtures/lib/index.js:54:5
    at f (/home/branie/Desktop/sabek/node_modules/once/once.js:17:25)
```

i get this error randomy

**Comment by devinivy** [comment]
This likely means that you're not using the right data format for your fixtures somewhere.  Check out this section of the docs: https://github.com/devinivy/waterline-fixtures#data-format.  Specifically, you're probably omitting the `model` key on one of your collection's fixtures.

**Comment by BransonGitomeh** [comment]
aah :-) sorry for the slow responce but i realize it was an issue with my code, was asking for a generator module i made for fixtures ,and not calling it as a function hence dogwater was getting `[Function]` instead of the generate fixture data, i have fixed it and i have to say this module is quite good and thanks for the patience :-) :+1:  ill now close this issue
